services:
  minecraft:  
    image: itzg/minecraft-server
    container_name: minecraft
    restart: unless-stopped
    volumes:
      - ${DOCKER_SERVICES_CONFIG_LOCATION}/minecraft:/data
    ports:
      - 25565:25565
    environment:
      MOTD: Kim is annoying
      EULA: "TRUE"
      VERSION: 1.20.4
      PVP: "false"
    profiles:
      - games