services:
  minecraft:  
    image: itzg/minecraft-server
    container_name: minecraft
    restart: unless-stopped
    volumes:
      - ${DOCKER_SERVICES_CONFIG_LOCATION}/minecraft:/data
    ports:
      - 25565:25565
    environment:
      MOTD: Kim is annoying
      EULA: "TRUE"
      # VERSION: 1.20.5
      PVP: "false"
      ENABLE_WHITELIST: "true"
      WHITELIST: MuffinsDaNarwhal,Allambee20,TheGuildedDodo,Kefe_Aikae,tigerattacker,OiM8itzCait,TheJuanNachO
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 5s
      retries: 20 
    profiles:
      - games
